### ISSUE TITLE
Ban user button without requiring database access

### ISSUE THREAD

**Issue by zorbathut** [themotte/tildes#26]
It currently seems like there's no way to ban a user without database access. We need a button for that, available to admins.

**Comment by Deimos** [comment]
There is one, you need to have the `user.ban` permission: https://github.com/themotte/tildes/blob/master/tildes/tildes/templates/user.jinja2#L192-L205

(Permissions are granted by inserting rows into the `user_permissions` table, that *does* require database access still)

**Comment by zorbathut** [comment]
Aha! Alright I'm just gonna go ahead and close this then, thanks :D
