### ISSUE TITLE
Disable invite-only functionality

### ISSUE THREAD

**Issue by zorbathut** [themotte/tildes#4]
People should just be able to make accounts.

Extra credit if there's an admin-level option somewhere so we can turn invite-only back on without having to bounce the servers.

**Comment by AI-WAIFU** [comment]
The registration check code can be found [here](https://github.com/themotte/tildes/blob/master/tildes/tildes/views/register.py#L76-L93).
Registration form code can be found [here](https://github.com/themotte/tildes/blob/master/tildes/tildes/templates/register.jinja2#L22-L25)

I think the fastest way to do this is to just scrap the relevant code and add a register link on the front page.
